# Generated by Django 3.0 on 2019-12-15 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField()),
            ],
            options={
                'verbose_name': 'フレンド',
                'verbose_name_plural': 'フレンド',
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='OutGo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='買った物')),
                ('price', models.IntegerField(default=0, verbose_name='値段')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'db_table': 'outgo',
            },
        ),
    ]
