# Generated by Django 3.0 on 2019-12-15 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191215_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgo',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
