# Generated by Django 3.0 on 2019-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191215_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgo',
            name='category',
            field=models.CharField(choices=[('その他', 'その他'), ('食費', '食費'), ('光熱費', '光熱費'), ('家賃', '家賃'), ('交際費', '交際費'), ('日用品', '日用品'), ('通信料', '通信料'), ('交通費', '交通費'), ('ファッション', 'ファッション'), ('趣味', '趣味')], default='その他', max_length=10, verbose_name='カテゴリ'),
            preserve_default=False,
        ),
    ]
